/* ═══════════════════════════════════════════════════════
   Smart Shopper — i18n Translations (50+ languages)
   ═══════════════════════════════════════════════════════ */

const SS_TRANSLATIONS = {
  // ─────── ENGLISH ───────
  en: { title:"Smart Shopper", scanning:"Scanning…", sameProduct:"Same product · other sellers", similarMatched:"Similar products · matched", related:"Related products", similarApi:"Similar products (API)", noAlt:"No alternatives", noProducts:"No products loaded", noProductsSub:"Scroll the page to load products, then click scan again.", scanAgain:"Scan again", bestValue:"Best value", cheapest:"Cheapest", bestDiscount:"Best discount", mostSold:"Most sold", cheapestTag:"Cheapest", bestDeal:"Best Deal", mostSoldTag:"Most Sold", bestValueTag:"Best Value", bestPrice:"Best Price", vs:"vs", sold:"sold", footer:"Prices as shown · We may earn a commission" },

  // ─────── ARABIC ───────
  ar: { title:"المتسوق الذكي", scanning:"جارٍ الفحص…", sameProduct:"نفس المنتج · بائعون آخرون", similarMatched:"منتجات مشابهة · مطابقة", related:"منتجات ذات صلة", similarApi:"منتجات مشابهة (API)", noAlt:"لا بدائل", noProducts:"لا توجد منتجات محمّلة", noProductsSub:"مرّر الصفحة لتحميل المنتجات، ثم اضغط فحص مجددًا.", scanAgain:"فحص مجددًا", bestValue:"أفضل قيمة", cheapest:"الأرخص", bestDiscount:"أعلى خصم", mostSold:"الأكثر مبيعًا", cheapestTag:"الأرخص", bestDeal:"أفضل صفقة", mostSoldTag:"الأكثر مبيعًا", bestValueTag:"أفضل قيمة", bestPrice:"أفضل سعر", vs:"مقابل", sold:"مباع", footer:"الأسعار كما هي معروضة · قد نحصل على عمولة" },

  // ─────── FRENCH ───────
  fr: { title:"Smart Shopper", scanning:"Analyse…", sameProduct:"Même produit · autres vendeurs", similarMatched:"Produits similaires · correspondance", related:"Produits liés", similarApi:"Produits similaires (API)", noAlt:"Aucune alternative", noProducts:"Aucun produit chargé", noProductsSub:"Faites défiler la page puis recliquez.", scanAgain:"Analyser à nouveau", bestValue:"Meilleur rapport", cheapest:"Moins cher", bestDiscount:"Meilleure remise", mostSold:"Plus vendu", cheapestTag:"Moins cher", bestDeal:"Meilleure offre", mostSoldTag:"Plus vendu", bestValueTag:"Meilleur rapport", bestPrice:"Meilleur prix", vs:"vs", sold:"vendus", footer:"Prix affichés · Commission possible" },

  // ─────── SPANISH ───────
  es: { title:"Smart Shopper", scanning:"Analizando…", sameProduct:"Mismo producto · otros vendedores", similarMatched:"Productos similares · coincidencia", related:"Productos relacionados", similarApi:"Productos similares (API)", noAlt:"Sin alternativas", noProducts:"No hay productos", noProductsSub:"Desplázate y vuelve a escanear.", scanAgain:"Escanear de nuevo", bestValue:"Mejor valor", cheapest:"Más barato", bestDiscount:"Mejor descuento", mostSold:"Más vendido", cheapestTag:"Más barato", bestDeal:"Mejor oferta", mostSoldTag:"Más vendido", bestValueTag:"Mejor valor", bestPrice:"Mejor precio", vs:"vs", sold:"vendidos", footer:"Precios mostrados · Comisión posible" },

  // ─────── GERMAN ───────
  de: { title:"Smart Shopper", scanning:"Scannen…", sameProduct:"Gleiches Produkt · andere Verkäufer", similarMatched:"Ähnliche Produkte · Übereinstimmung", related:"Verwandte Produkte", similarApi:"Ähnliche Produkte (API)", noAlt:"Keine Alternativen", noProducts:"Keine Produkte geladen", noProductsSub:"Scrolle die Seite, dann erneut scannen.", scanAgain:"Erneut scannen", bestValue:"Bester Wert", cheapest:"Günstigster", bestDiscount:"Bester Rabatt", mostSold:"Meistverkauft", cheapestTag:"Günstigster", bestDeal:"Bestes Angebot", mostSoldTag:"Meistverkauft", bestValueTag:"Bester Wert", bestPrice:"Bester Preis", vs:"vs", sold:"verkauft", footer:"Preise wie angezeigt · Provision möglich" },

  // ─────── CHINESE SIMPLIFIED ───────
  zh: { title:"智能购物助手", scanning:"扫描中…", sameProduct:"相同产品 · 其他卖家", similarMatched:"相似产品 · 已匹配", related:"相关产品", similarApi:"相似产品（API）", noAlt:"无替代品", noProducts:"未加载产品", noProductsSub:"滚动页面加载产品，然后再次扫描。", scanAgain:"再次扫描", bestValue:"最佳性价比", cheapest:"最便宜", bestDiscount:"最佳折扣", mostSold:"最畅销", cheapestTag:"最便宜", bestDeal:"最佳交易", mostSoldTag:"最畅销", bestValueTag:"最佳性价比", bestPrice:"最佳价格", vs:"对比", sold:"已售", footer:"价格为页面显示 · 我们可能获得佣金" },

  // ─────── CHINESE TRADITIONAL ───────
  "zh-tw": { title:"智能購物助手", scanning:"掃描中…", sameProduct:"相同產品 · 其他賣家", similarMatched:"相似產品 · 已匹配", related:"相關產品", similarApi:"相似產品（API）", noAlt:"無替代品", noProducts:"未載入產品", noProductsSub:"滾動頁面載入產品，然後再次掃描。", scanAgain:"再次掃描", bestValue:"最佳性價比", cheapest:"最便宜", bestDiscount:"最佳折扣", mostSold:"最暢銷", cheapestTag:"最便宜", bestDeal:"最佳交易", mostSoldTag:"最暢銷", bestValueTag:"最佳性價比", bestPrice:"最佳價格", vs:"對比", sold:"已售", footer:"價格為頁面顯示 · 我們可能獲得佣金" },

  // ─────── JAPANESE ───────
  ja: { title:"スマートショッパー", scanning:"スキャン中…", sameProduct:"同じ商品 · 他の販売者", similarMatched:"類似商品 · 一致", related:"関連商品", similarApi:"類似商品（API）", noAlt:"代替品なし", noProducts:"商品が読み込まれていません", noProductsSub:"ページをスクロールして再スキャンしてください。", scanAgain:"再スキャン", bestValue:"最高の価値", cheapest:"最安値", bestDiscount:"最大割引", mostSold:"最も売れた", cheapestTag:"最安値", bestDeal:"ベストディール", mostSoldTag:"最も売れた", bestValueTag:"最高の価値", bestPrice:"ベストプライス", vs:"対", sold:"販売済み", footer:"表示価格 · 手数料を得る場合があります" },

  // ─────── KOREAN ───────
  ko: { title:"스마트 쇼퍼", scanning:"스캔 중…", sameProduct:"동일 제품 · 다른 판매자", similarMatched:"유사 제품 · 매칭", related:"관련 제품", similarApi:"유사 제품 (API)", noAlt:"대안 없음", noProducts:"로드된 제품 없음", noProductsSub:"페이지를 스크롤한 후 다시 스캔하세요.", scanAgain:"다시 스캔", bestValue:"최고 가치", cheapest:"최저가", bestDiscount:"최대 할인", mostSold:"최다 판매", cheapestTag:"최저가", bestDeal:"최고 거래", mostSoldTag:"최다 판매", bestValueTag:"최고 가치", bestPrice:"최적 가격", vs:"대비", sold:"판매됨", footer:"표시된 가격 · 수수료를 받을 수 있습니다" },

  // ─────── MALAY ───────
  ms: { title:"Pembeli Pintar", scanning:"Mengimbas…", sameProduct:"Produk sama · penjual lain", similarMatched:"Produk serupa · dipadankan", related:"Produk berkaitan", similarApi:"Produk serupa (API)", noAlt:"Tiada alternatif", noProducts:"Tiada produk dimuatkan", noProductsSub:"Tatal halaman kemudian imbas semula.", scanAgain:"Imbas semula", bestValue:"Nilai terbaik", cheapest:"Termurah", bestDiscount:"Diskaun terbaik", mostSold:"Paling laris", cheapestTag:"Termurah", bestDeal:"Tawaran terbaik", mostSoldTag:"Paling laris", bestValueTag:"Nilai terbaik", bestPrice:"Harga terbaik", vs:"vs", sold:"terjual", footer:"Harga seperti dipaparkan · Kami boleh dapat komisen" },

  // ─────── INDONESIAN ───────
  id: { title:"Pembeli Pintar", scanning:"Memindai…", sameProduct:"Produk sama · penjual lain", similarMatched:"Produk serupa · cocok", related:"Produk terkait", similarApi:"Produk serupa (API)", noAlt:"Tidak ada alternatif", noProducts:"Tidak ada produk dimuat", noProductsSub:"Gulir halaman lalu pindai lagi.", scanAgain:"Pindai lagi", bestValue:"Nilai terbaik", cheapest:"Termurah", bestDiscount:"Diskon terbaik", mostSold:"Paling laris", cheapestTag:"Termurah", bestDeal:"Penawaran terbaik", mostSoldTag:"Paling laris", bestValueTag:"Nilai terbaik", bestPrice:"Harga terbaik", vs:"vs", sold:"terjual", footer:"Harga seperti ditampilkan · Komisi mungkin" },

  // ─────── THAI ───────
  th: { title:"สมาร์ทช้อปเปอร์", scanning:"กำลังสแกน…", sameProduct:"สินค้าเดียวกัน · ผู้ขายอื่น", similarMatched:"สินค้าคล้ายกัน · จับคู่", related:"สินค้าที่เกี่ยวข้อง", similarApi:"สินค้าคล้ายกัน (API)", noAlt:"ไม่มีทางเลือก", noProducts:"ไม่มีสินค้าโหลด", noProductsSub:"เลื่อนหน้าแล้วสแกนใหม่", scanAgain:"สแกนใหม่", bestValue:"คุ้มที่สุด", cheapest:"ถูกที่สุด", bestDiscount:"ส่วนลดดีที่สุด", mostSold:"ขายดีที่สุด", cheapestTag:"ถูกที่สุด", bestDeal:"ดีลที่ดีที่สุด", mostSoldTag:"ขายดีที่สุด", bestValueTag:"คุ้มที่สุด", bestPrice:"ราคาดีที่สุด", vs:"เทียบ", sold:"ขายแล้ว", footer:"ราคาตามที่แสดง · เราอาจได้ค่าคอมมิชชั่น" },

  // ─────── VIETNAMESE ───────
  vi: { title:"Người mua thông minh", scanning:"Đang quét…", sameProduct:"Cùng sản phẩm · người bán khác", similarMatched:"Sản phẩm tương tự · khớp", related:"Sản phẩm liên quan", similarApi:"Sản phẩm tương tự (API)", noAlt:"Không có thay thế", noProducts:"Không có sản phẩm", noProductsSub:"Cuộn trang rồi quét lại.", scanAgain:"Quét lại", bestValue:"Giá trị tốt nhất", cheapest:"Rẻ nhất", bestDiscount:"Giảm giá tốt nhất", mostSold:"Bán chạy nhất", cheapestTag:"Rẻ nhất", bestDeal:"Ưu đãi tốt nhất", mostSoldTag:"Bán chạy nhất", bestValueTag:"Giá trị tốt nhất", bestPrice:"Giá tốt nhất", vs:"so với", sold:"đã bán", footer:"Giá như hiển thị · Chúng tôi có thể nhận hoa hồng" },

  // ─────── TURKISH ───────
  tr: { title:"Akıllı Alışveriş", scanning:"Taranıyor…", sameProduct:"Aynı ürün · diğer satıcılar", similarMatched:"Benzer ürünler · eşleşti", related:"İlgili ürünler", similarApi:"Benzer ürünler (API)", noAlt:"Alternatif yok", noProducts:"Yüklü ürün yok", noProductsSub:"Sayfayı kaydırın ve tekrar tarayın.", scanAgain:"Tekrar tara", bestValue:"En iyi değer", cheapest:"En ucuz", bestDiscount:"En iyi indirim", mostSold:"En çok satan", cheapestTag:"En ucuz", bestDeal:"En iyi fırsat", mostSoldTag:"En çok satan", bestValueTag:"En iyi değer", bestPrice:"En iyi fiyat", vs:"vs", sold:"satıldı", footer:"Gösterilen fiyatlar · Komisyon kazanabiliriz" },

  // ─────── RUSSIAN ───────
  ru: { title:"Smart Shopper", scanning:"Сканирование…", sameProduct:"Тот же товар · другие продавцы", similarMatched:"Похожие товары · совпадение", related:"Связанные товары", similarApi:"Похожие товары (API)", noAlt:"Нет альтернатив", noProducts:"Товары не загружены", noProductsSub:"Прокрутите страницу и сканируйте снова.", scanAgain:"Сканировать снова", bestValue:"Лучшее предложение", cheapest:"Самый дешёвый", bestDiscount:"Лучшая скидка", mostSold:"Самый продаваемый", cheapestTag:"Самый дешёвый", bestDeal:"Лучшая сделка", mostSoldTag:"Самый продаваемый", bestValueTag:"Лучшее предложение", bestPrice:"Лучшая цена", vs:"против", sold:"продано", footer:"Цены как показано · Возможна комиссия" },

  // ─────── PORTUGUESE ───────
  pt: { title:"Comprador Inteligente", scanning:"Analisando…", sameProduct:"Mesmo produto · outros vendedores", similarMatched:"Produtos similares · correspondência", related:"Produtos relacionados", similarApi:"Produtos similares (API)", noAlt:"Sem alternativas", noProducts:"Nenhum produto carregado", noProductsSub:"Role a página e escaneie novamente.", scanAgain:"Escanear novamente", bestValue:"Melhor valor", cheapest:"Mais barato", bestDiscount:"Melhor desconto", mostSold:"Mais vendido", cheapestTag:"Mais barato", bestDeal:"Melhor oferta", mostSoldTag:"Mais vendido", bestValueTag:"Melhor valor", bestPrice:"Melhor preço", vs:"vs", sold:"vendidos", footer:"Preços exibidos · Podemos ganhar comissão" },

  // ─────── ITALIAN ───────
  it: { title:"Smart Shopper", scanning:"Scansione…", sameProduct:"Stesso prodotto · altri venditori", similarMatched:"Prodotti simili · corrispondenza", related:"Prodotti correlati", similarApi:"Prodotti simili (API)", noAlt:"Nessuna alternativa", noProducts:"Nessun prodotto caricato", noProductsSub:"Scorri la pagina e scansiona di nuovo.", scanAgain:"Scansiona di nuovo", bestValue:"Miglior valore", cheapest:"Più economico", bestDiscount:"Miglior sconto", mostSold:"Più venduto", cheapestTag:"Più economico", bestDeal:"Migliore offerta", mostSoldTag:"Più venduto", bestValueTag:"Miglior valore", bestPrice:"Miglior prezzo", vs:"vs", sold:"venduti", footer:"Prezzi come mostrati · Commissione possibile" },

  // ─────── DUTCH ───────
  nl: { title:"Slimme Shopper", scanning:"Scannen…", sameProduct:"Zelfde product · andere verkopers", similarMatched:"Vergelijkbare producten · match", related:"Gerelateerde producten", similarApi:"Vergelijkbare producten (API)", noAlt:"Geen alternatieven", noProducts:"Geen producten geladen", noProductsSub:"Scroll de pagina en scan opnieuw.", scanAgain:"Opnieuw scannen", bestValue:"Beste waarde", cheapest:"Goedkoopste", bestDiscount:"Beste korting", mostSold:"Meest verkocht", cheapestTag:"Goedkoopste", bestDeal:"Beste deal", mostSoldTag:"Meest verkocht", bestValueTag:"Beste waarde", bestPrice:"Beste prijs", vs:"vs", sold:"verkocht", footer:"Prijzen zoals weergegeven · Commissie mogelijk" },

  // ─────── POLISH ───────
  pl: { title:"Smart Shopper", scanning:"Skanowanie…", sameProduct:"Ten sam produkt · inni sprzedawcy", similarMatched:"Podobne produkty · dopasowane", related:"Powiązane produkty", similarApi:"Podobne produkty (API)", noAlt:"Brak alternatyw", noProducts:"Brak produktów", noProductsSub:"Przewiń stronę i skanuj ponownie.", scanAgain:"Skanuj ponownie", bestValue:"Najlepsza wartość", cheapest:"Najtańszy", bestDiscount:"Najlepsza zniżka", mostSold:"Najczęściej sprzedawany", cheapestTag:"Najtańszy", bestDeal:"Najlepsza oferta", mostSoldTag:"Najczęściej sprzedawany", bestValueTag:"Najlepsza wartość", bestPrice:"Najlepsza cena", vs:"vs", sold:"sprzedano", footer:"Ceny jak pokazano · Możliwa prowizja" },

  // ─────── UKRAINIAN ───────
  uk: { title:"Smart Shopper", scanning:"Сканування…", sameProduct:"Той самий товар · інші продавці", similarMatched:"Схожі товари · збіг", related:"Пов'язані товари", similarApi:"Схожі товари (API)", noAlt:"Немає альтернатив", noProducts:"Товари не завантажено", noProductsSub:"Прокрутіть сторінку та скануйте знову.", scanAgain:"Сканувати знову", bestValue:"Найкраща цінність", cheapest:"Найдешевший", bestDiscount:"Найкраща знижка", mostSold:"Найбільш продаваний", cheapestTag:"Найдешевший", bestDeal:"Найкраща угода", mostSoldTag:"Найбільш продаваний", bestValueTag:"Найкраща цінність", bestPrice:"Найкраща ціна", vs:"проти", sold:"продано", footer:"Ціни як показано · Можлива комісія" },

  // ─────── HINDI ───────
  hi: { title:"स्मार्ट शॉपर", scanning:"स्कैन हो रहा है…", sameProduct:"वही उत्पाद · अन्य विक्रेता", similarMatched:"समान उत्पाद · मिलान", related:"संबंधित उत्पाद", similarApi:"समान उत्पाद (API)", noAlt:"कोई विकल्प नहीं", noProducts:"कोई उत्पाद लोड नहीं", noProductsSub:"पेज स्क्रॉल करें और फिर स्कैन करें।", scanAgain:"फिर स्कैन करें", bestValue:"सर्वोत्तम मूल्य", cheapest:"सबसे सस्ता", bestDiscount:"सर्वोत्तम छूट", mostSold:"सर्वाधिक बिकने वाला", cheapestTag:"सबसे सस्ता", bestDeal:"सर्वोत्तम सौदा", mostSoldTag:"सर्वाधिक बिकने वाला", bestValueTag:"सर्वोत्तम मूल्य", bestPrice:"सर्वोत्तम मूल्य", vs:"बनाम", sold:"बिके", footer:"दिखाए गए मूल्य · कमीशन संभव" },

  // ─────── BENGALI ───────
  bn: { title:"স্মার্ট শপার", scanning:"স্ক্যান করা হচ্ছে…", sameProduct:"একই পণ্য · অন্যান্য বিক্রেতা", similarMatched:"অনুরূপ পণ্য · মিল", related:"সংশ্লিষ্ট পণ্য", similarApi:"অনুরূপ পণ্য (API)", noAlt:"কোনো বিকল্প নেই", noProducts:"কোনো পণ্য লোড হয়নি", noProductsSub:"পৃষ্ঠা স্ক্রল করুন এবং আবার স্ক্যান করুন।", scanAgain:"আবার স্ক্যান করুন", bestValue:"সর্বোত্তম মূল্য", cheapest:"সবচেয়ে সস্তা", bestDiscount:"সেরা ছাড়", mostSold:"সর্বাধিক বিক্রীত", cheapestTag:"সবচেয়ে সস্তা", bestDeal:"সেরা ডিল", mostSoldTag:"সর্বাধিক বিক্রীত", bestValueTag:"সর্বোত্তম মূল্য", bestPrice:"সেরা মূল্য", vs:"বনাম", sold:"বিক্রি", footer:"দেখানো মূল্য · কমিশন সম্ভব" },

  // ─────── URDU ───────
  ur: { title:"سمارٹ شاپر", scanning:"اسکین ہو رہا ہے…", sameProduct:"ایک ہی مصنوع · دوسرے فروخت کنندگان", similarMatched:"ملتی جلتی مصنوعات · میچ", related:"متعلقہ مصنوعات", similarApi:"ملتی جلتی مصنوعات (API)", noAlt:"کوئی متبادل نہیں", noProducts:"کوئی مصنوع لوڈ نہیں", noProductsSub:"صفحہ اسکرول کریں، پھر دوبارہ اسکین کریں۔", scanAgain:"دوبارہ اسکین کریں", bestValue:"بہترین قیمت", cheapest:"سب سے سستا", bestDiscount:"بہترین رعایت", mostSold:"سب سے زیادہ فروخت", cheapestTag:"سب سے سستا", bestDeal:"بہترین سودا", mostSoldTag:"سب سے زیادہ فروخت", bestValueTag:"بہترین قیمت", bestPrice:"بہترین قیمت", vs:"بمقابلہ", sold:"فروخت", footer:"دکھائی گئی قیمتیں · کمیشن ممکن ہے" },

  // ─────── PERSIAN ───────
  fa: { title:"خریدار هوشمند", scanning:"در حال اسکن…", sameProduct:"همان محصول · فروشندگان دیگر", similarMatched:"محصولات مشابه · منطبق", related:"محصولات مرتبط", similarApi:"محصولات مشابه (API)", noAlt:"بدون جایگزین", noProducts:"محصولی بارگذاری نشد", noProductsSub:"صفحه را اسکرول کنید و دوباره اسکن کنید.", scanAgain:"اسکن مجدد", bestValue:"بهترین ارزش", cheapest:"ارزان‌ترین", bestDiscount:"بهترین تخفیف", mostSold:"پرفروش‌ترین", cheapestTag:"ارزان‌ترین", bestDeal:"بهترین معامله", mostSoldTag:"پرفروش‌ترین", bestValueTag:"بهترین ارزش", bestPrice:"بهترین قیمت", vs:"در برابر", sold:"فروش", footer:"قیمت‌های نمایش‌داده شده · کمیسیون ممکن است" },

  // ─────── HEBREW ───────
  he: { title:"קונה חכם", scanning:"סורק…", sameProduct:"אותו מוצר · מוכרים אחרים", similarMatched:"מוצרים דומים · התאמה", related:"מוצרים קשורים", similarApi:"מוצרים דומים (API)", noAlt:"אין חלופות", noProducts:"לא נטענו מוצרים", noProductsSub:"גלול את הדף וסרוק שוב.", scanAgain:"סרוק שוב", bestValue:"הערך הטוב ביותר", cheapest:"הזול ביותר", bestDiscount:"ההנחה הטובה ביותר", mostSold:"הנמכר ביותר", cheapestTag:"הזול ביותר", bestDeal:"העסקה הטובה ביותר", mostSoldTag:"הנמכר ביותר", bestValueTag:"הערך הטוב ביותר", bestPrice:"המחיר הטוב ביותר", vs:"מול", sold:"נמכר", footer:"מחירים כפי שמוצגים · עמלה אפשרית" },

  // ─────── GREEK ───────
  el: { title:"Έξυπνος Αγοραστής", scanning:"Σάρωση…", sameProduct:"Ίδιο προϊόν · άλλοι πωλητές", similarMatched:"Παρόμοια προϊόντα · αντιστοίχιση", related:"Σχετικά προϊόντα", similarApi:"Παρόμοια προϊόντα (API)", noAlt:"Καμία εναλλακτική", noProducts:"Δεν φορτώθηκαν προϊόντα", noProductsSub:"Κύλισε τη σελίδα και σάρωσε ξανά.", scanAgain:"Σάρωση ξανά", bestValue:"Καλύτερη αξία", cheapest:"Φθηνότερο", bestDiscount:"Καλύτερη έκπτωση", mostSold:"Περισσότερο πουλημένο", cheapestTag:"Φθηνότερο", bestDeal:"Καλύτερη προσφορά", mostSoldTag:"Περισσότερο πουλημένο", bestValueTag:"Καλύτερη αξία", bestPrice:"Καλύτερη τιμή", vs:"vs", sold:"πωλήθηκαν", footer:"Τιμές όπως εμφανίζονται · Προμήθεια πιθανή" },

  // ─────── SWEDISH ───────
  sv: { title:"Smart Shopper", scanning:"Skannar…", sameProduct:"Samma produkt · andra säljare", similarMatched:"Liknande produkter · matchade", related:"Relaterade produkter", similarApi:"Liknande produkter (API)", noAlt:"Inga alternativ", noProducts:"Inga produkter laddade", noProductsSub:"Scrolla sidan och skanna igen.", scanAgain:"Skanna igen", bestValue:"Bästa värde", cheapest:"Billigaste", bestDiscount:"Bästa rabatten", mostSold:"Mest såld", cheapestTag:"Billigaste", bestDeal:"Bästa erbjudandet", mostSoldTag:"Mest såld", bestValueTag:"Bästa värde", bestPrice:"Bästa pris", vs:"vs", sold:"sålda", footer:"Priser som visade · Provision möjlig" },

  // ─────── NORWEGIAN ───────
  no: { title:"Smart Shopper", scanning:"Skanner…", sameProduct:"Samme produkt · andre selgere", similarMatched:"Lignende produkter · matchet", related:"Relaterte produkter", similarApi:"Lignende produkter (API)", noAlt:"Ingen alternativer", noProducts:"Ingen produkter lastet", noProductsSub:"Rull siden og skann på nytt.", scanAgain:"Skann på nytt", bestValue:"Beste verdi", cheapest:"Billigst", bestDiscount:"Beste rabatt", mostSold:"Mest solgt", cheapestTag:"Billigst", bestDeal:"Beste tilbud", mostSoldTag:"Mest solgt", bestValueTag:"Beste verdi", bestPrice:"Beste pris", vs:"vs", sold:"solgt", footer:"Priser som vist · Provisjon mulig" },

  // ─────── DANISH ───────
  da: { title:"Smart Shopper", scanning:"Scanner…", sameProduct:"Samme produkt · andre sælgere", similarMatched:"Lignende produkter · matchet", related:"Relaterede produkter", similarApi:"Lignende produkter (API)", noAlt:"Ingen alternativer", noProducts:"Ingen produkter indlæst", noProductsSub:"Rul siden og scan igen.", scanAgain:"Scan igen", bestValue:"Bedste værdi", cheapest:"Billigste", bestDiscount:"Bedste rabat", mostSold:"Mest solgt", cheapestTag:"Billigste", bestDeal:"Bedste tilbud", mostSoldTag:"Mest solgt", bestValueTag:"Bedste værdi", bestPrice:"Bedste pris", vs:"vs", sold:"solgt", footer:"Priser som vist · Provision mulig" },

  // ─────── FINNISH ───────
  fi: { title:"Älykäs ostaja", scanning:"Skannataan…", sameProduct:"Sama tuote · muut myyjät", similarMatched:"Samankaltaiset tuotteet · täsmäytetyt", related:"Aiheeseen liittyvät", similarApi:"Samankaltaiset tuotteet (API)", noAlt:"Ei vaihtoehtoja", noProducts:"Ei tuotteita ladattu", noProductsSub:"Vieritä sivua ja skannaa uudelleen.", scanAgain:"Skannaa uudelleen", bestValue:"Paras arvo", cheapest:"Halvin", bestDiscount:"Paras alennus", mostSold:"Myydyin", cheapestTag:"Halvin", bestDeal:"Paras tarjous", mostSoldTag:"Myydyin", bestValueTag:"Paras arvo", bestPrice:"Paras hinta", vs:"vs", sold:"myyty", footer:"Hinnat kuten näytetty · Provisio mahdollinen" },

  // ─────── CZECH ───────
  cs: { title:"Smart Shopper", scanning:"Skenování…", sameProduct:"Stejný produkt · jiní prodejci", similarMatched:"Podobné produkty · shoda", related:"Související produkty", similarApi:"Podobné produkty (API)", noAlt:"Žádné alternativy", noProducts:"Žádné produkty", noProductsSub:"Posuňte stránku a skenujte znovu.", scanAgain:"Skenovat znovu", bestValue:"Nejlepší hodnota", cheapest:"Nejlevnější", bestDiscount:"Nejlepší sleva", mostSold:"Nejprodávanější", cheapestTag:"Nejlevnější", bestDeal:"Nejlepší nabídka", mostSoldTag:"Nejprodávanější", bestValueTag:"Nejlepší hodnota", bestPrice:"Nejlepší cena", vs:"vs", sold:"prodáno", footer:"Ceny jak zobrazeno · Provize možná" },

  // ─────── HUNGARIAN ───────
  hu: { title:"Okos Vásárló", scanning:"Szkennelés…", sameProduct:"Ugyanaz a termék · más eladók", similarMatched:"Hasonló termékek · egyezés", related:"Kapcsolódó termékek", similarApi:"Hasonló termékek (API)", noAlt:"Nincs alternatíva", noProducts:"Nincs betöltött termék", noProductsSub:"Görgessen és szkenneljen újra.", scanAgain:"Újraszkennelés", bestValue:"Legjobb érték", cheapest:"Legolcsóbb", bestDiscount:"Legjobb kedvezmény", mostSold:"Legkelendőbb", cheapestTag:"Legolcsóbb", bestDeal:"Legjobb ajánlat", mostSoldTag:"Legkelendőbb", bestValueTag:"Legjobb érték", bestPrice:"Legjobb ár", vs:"vs", sold:"eladva", footer:"Mutatott árak · Jutalék lehetséges" },

  // ─────── ROMANIAN ───────
  ro: { title:"Smart Shopper", scanning:"Se scanează…", sameProduct:"Același produs · alți vânzători", similarMatched:"Produse similare · potrivite", related:"Produse conexe", similarApi:"Produse similare (API)", noAlt:"Fără alternative", noProducts:"Niciun produs încărcat", noProductsSub:"Derulați pagina și scanați din nou.", scanAgain:"Scanați din nou", bestValue:"Cea mai bună valoare", cheapest:"Cel mai ieftin", bestDiscount:"Cea mai bună reducere", mostSold:"Cel mai vândut", cheapestTag:"Cel mai ieftin", bestDeal:"Cea mai bună ofertă", mostSoldTag:"Cel mai vândut", bestValueTag:"Cea mai bună valoare", bestPrice:"Cel mai bun preț", vs:"vs", sold:"vândute", footer:"Prețuri afișate · Comision posibil" },

  // ─────── BULGARIAN ───────
  bg: { title:"Умен Пазарувач", scanning:"Сканиране…", sameProduct:"Същият продукт · други продавачи", similarMatched:"Подобни продукти · съвпадение", related:"Свързани продукти", similarApi:"Подобни продукти (API)", noAlt:"Без алтернативи", noProducts:"Няма заредени продукти", noProductsSub:"Превъртете страницата и сканирайте отново.", scanAgain:"Сканирай отново", bestValue:"Най-добра стойност", cheapest:"Най-евтин", bestDiscount:"Най-добра отстъпка", mostSold:"Най-продаван", cheapestTag:"Най-евтин", bestDeal:"Най-добра сделка", mostSoldTag:"Най-продаван", bestValueTag:"Най-добра стойност", bestPrice:"Най-добра цена", vs:"срещу", sold:"продадени", footer:"Цени както са показани · Възможна комисионна" },

  // ─────── CROATIAN ───────
  hr: { title:"Pametni Kupac", scanning:"Skeniranje…", sameProduct:"Isti proizvod · drugi prodavači", similarMatched:"Slični proizvodi · podudaranje", related:"Povezani proizvodi", similarApi:"Slični proizvodi (API)", noAlt:"Nema alternativa", noProducts:"Nema učitanih proizvoda", noProductsSub:"Pomaknite stranicu i skenirajte ponovno.", scanAgain:"Skeniraj ponovno", bestValue:"Najbolja vrijednost", cheapest:"Najjeftiniji", bestDiscount:"Najbolji popust", mostSold:"Najprodavaniji", cheapestTag:"Najjeftiniji", bestDeal:"Najbolja ponuda", mostSoldTag:"Najprodavaniji", bestValueTag:"Najbolja vrijednost", bestPrice:"Najbolja cijena", vs:"vs", sold:"prodano", footer:"Cijene kako prikazano · Provizija moguća" },

  // ─────── SERBIAN ───────
  sr: { title:"Паметни Купац", scanning:"Скенирање…", sameProduct:"Исти производ · други продавци", similarMatched:"Слични производи · подударање", related:"Повезани производи", similarApi:"Слични производи (API)", noAlt:"Нема алтернатива", noProducts:"Нема учитаних производа", noProductsSub:"Померите страницу и скенирајте поново.", scanAgain:"Скенирај поново", bestValue:"Најбоља вредност", cheapest:"Најјефтинији", bestDiscount:"Најбољи попуст", mostSold:"Најпродаванији", cheapestTag:"Најјефтинији", bestDeal:"Најбоља понуда", mostSoldTag:"Најпродаванији", bestValueTag:"Најбоља вредност", bestPrice:"Најбоља цена", vs:"vs", sold:"продато", footer:"Цене како приказано · Провиднија могућа" },

  // ─────── SLOVAK ───────
  sk: { title:"Smart Shopper", scanning:"Skenovanie…", sameProduct:"Rovnaký produkt · iní predajcovia", similarMatched:"Podobné produkty · zhoda", related:"Súvisiace produkty", similarApi:"Podobné produkty (API)", noAlt:"Žiadne alternatívy", noProducts:"Žiadne produkty", noProductsSub:"Posuňte stránku a skenujte znova.", scanAgain:"Skenovať znova", bestValue:"Najlepšia hodnota", cheapest:"Najlacnejší", bestDiscount:"Najlepšia zľava", mostSold:"Najpredávanejší", cheapestTag:"Najlacnejší", bestDeal:"Najlepšia ponuka", mostSoldTag:"Najpredávanejší", bestValueTag:"Najlepšia hodnota", bestPrice:"Najlepšia cena", vs:"vs", sold:"predané", footer:"Ceny ako zobrazené · Provízia možná" },

  // ─────── SLOVENIAN ───────
  sl: { title:"Pametni Kupec", scanning:"Skeniranje…", sameProduct:"Isti izdelek · drugi prodajalci", similarMatched:"Podobni izdelki · ujemanje", related:"Povezani izdelki", similarApi:"Podobni izdelki (API)", noAlt:"Ni alternative", noProducts:"Ni naloženih izdelkov", noProductsSub:"Pomaknite stran in znova skenirajte.", scanAgain:"Skeniraj znova", bestValue:"Najboljša vrednost", cheapest:"Najcenejši", bestDiscount:"Najboljši popust", mostSold:"Najbolje prodajan", cheapestTag:"Najcenejši", bestDeal:"Najboljša ponudba", mostSoldTag:"Najbolje prodajan", bestValueTag:"Najboljša vrednost", bestPrice:"Najboljša cena", vs:"vs", sold:"prodano", footer:"Cene kot prikazano · Provizija možna" },

  // ─────── LITHUANIAN ───────
  lt: { title:"Išmanusis Pirkėjas", scanning:"Skenuojama…", sameProduct:"Tas pats produktas · kiti pardavėjai", similarMatched:"Panašūs produktai · atitikimas", related:"Susiję produktai", similarApi:"Panašūs produktai (API)", noAlt:"Nėra alternatyvų", noProducts:"Nėra įkeltų produktų", noProductsSub:"Slinkite puslapį ir skenuokite iš naujo.", scanAgain:"Skenuoti iš naujo", bestValue:"Geriausia vertė", cheapest:"Pigiausias", bestDiscount:"Geriausia nuolaida", mostSold:"Daugiausiai parduotas", cheapestTag:"Pigiausias", bestDeal:"Geriausias pasiūlymas", mostSoldTag:"Daugiausiai parduotas", bestValueTag:"Geriausia vertė", bestPrice:"Geriausia kaina", vs:"vs", sold:"parduota", footer:"Kainos kaip rodoma · Galimas komisinis" },

  // ─────── LATVIAN ───────
  lv: { title:"Viedais Pircējs", scanning:"Skenē…", sameProduct:"Tas pats produkts · citi pārdevēji", similarMatched:"Līdzīgi produkti · atbilstība", related:"Saistītie produkti", similarApi:"Līdzīgi produkti (API)", noAlt:"Nav alternatīvu", noProducts:"Nav ielādētu produktu", noProductsSub:"Ritiniet lapu un skenējiet vēlreiz.", scanAgain:"Skenēt vēlreiz", bestValue:"Labākā vērtība", cheapest:"Lētākais", bestDiscount:"Labākā atlaide", mostSold:"Visvairāk pārdots", cheapestTag:"Lētākais", bestDeal:"Labākais piedāvājums", mostSoldTag:"Visvairāk pārdots", bestValueTag:"Labākā vērtība", bestPrice:"Labākā cena", vs:"vs", sold:"pārdots", footer:"Cenas kā parādīts · Iespējama komisija" },

  // ─────── ESTONIAN ───────
  et: { title:"Nutikas Ostja", scanning:"Skaneerimine…", sameProduct:"Sama toode · teised müüjad", similarMatched:"Sarnased tooted · sobivus", related:"Seotud tooted", similarApi:"Sarnased tooted (API)", noAlt:"Alternatiive pole", noProducts:"Tooteid pole laaditud", noProductsSub:"Kerige lehte ja skaneerige uuesti.", scanAgain:"Skaneeri uuesti", bestValue:"Parim väärtus", cheapest:"Odavaim", bestDiscount:"Parim allahindlus", mostSold:"Enim müüdud", cheapestTag:"Odavaim", bestDeal:"Parim pakkumine", mostSoldTag:"Enim müüdud", bestValueTag:"Parim väärtus", bestPrice:"Parim hind", vs:"vs", sold:"müüdud", footer:"Hinnad nagu näidatud · Vahendustasu võimalik" },

  // ─────── AZERBAIJANI ───────
  az: { title:"Ağıllı Alıcı", scanning:"Skan edilir…", sameProduct:"Eyni məhsul · digər satıcılar", similarMatched:"Bənzər məhsullar · uyğun", related:"Əlaqəli məhsullar", similarApi:"Bənzər məhsullar (API)", noAlt:"Alternativ yoxdur", noProducts:"Yüklənmiş məhsul yoxdur", noProductsSub:"Səhifəni sürüşdürün və yenidən skan edin.", scanAgain:"Yenidən skan et", bestValue:"Ən yaxşı dəyər", cheapest:"Ən ucuz", bestDiscount:"Ən yaxşı endirim", mostSold:"Ən çox satılan", cheapestTag:"Ən ucuz", bestDeal:"Ən yaxşı təklif", mostSoldTag:"Ən çox satılan", bestValueTag:"Ən yaxşı dəyər", bestPrice:"Ən yaxşı qiymət", vs:"vs", sold:"satıldı", footer:"Göstərilən qiymətlər · Komissiya mümkündür" },

  // ─────── KAZAKH ───────
  kk: { title:"Ақылды Сатып алушы", scanning:"Сканерлеу…", sameProduct:"Бірдей өнім · басқа сатушылар", similarMatched:"Ұқсас өнімдер · сәйкестік", related:"Қатысты өнімдер", similarApi:"Ұқсас өнімдер (API)", noAlt:"Балама жоқ", noProducts:"Өнімдер жүктелмеген", noProductsSub:"Бетті айналдырып, қайта сканерлеңіз.", scanAgain:"Қайта сканерлеу", bestValue:"Ең жақсы құн", cheapest:"Ең арзан", bestDiscount:"Ең жақсы жеңілдік", mostSold:"Ең көп сатылған", cheapestTag:"Ең арзан", bestDeal:"Ең жақсы мәміле", mostSoldTag:"Ең көп сатылған", bestValueTag:"Ең жақсы құн", bestPrice:"Ең жақсы баға", vs:"vs", sold:"сатылды", footer:"Көрсетілген бағалар · Комиссия мүмкін" },

  // ─────── UZBEK ───────
  uz: { title:"Aqlli Xaridor", scanning:"Skanerlanmoqda…", sameProduct:"Xuddi shu mahsulot · boshqa sotuvchilar", similarMatched:"O'xshash mahsulotlar · mos", related:"Tegishli mahsulotlar", similarApi:"O'xshash mahsulotlar (API)", noAlt:"Alternativalar yo'q", noProducts:"Mahsulotlar yuklanmagan", noProductsSub:"Sahifani aylantiring va qayta skanerlang.", scanAgain:"Qayta skanerlash", bestValue:"Eng yaxshi qiymat", cheapest:"Eng arzon", bestDiscount:"Eng yaxshi chegirma", mostSold:"Eng ko'p sotilgan", cheapestTag:"Eng arzon", bestDeal:"Eng yaxshi taklif", mostSoldTag:"Eng ko'p sotilgan", bestValueTag:"Eng yaxshi qiymat", bestPrice:"Eng yaxshi narx", vs:"vs", sold:"sotilgan", footer:"Ko'rsatilgan narxlar · Komissiya mumkin" },

  // ─────── GEORGIAN ───────
  ka: { title:"ჭკვიანი მყიდველი", scanning:"სკანირება…", sameProduct:"იგივე პროდუქტი · სხვა გამყიდველები", similarMatched:"მსგავსი პროდუქტები · დამთხვევა", related:"დაკავშირებული პროდუქტები", similarApi:"მსგავსი პროდუქტები (API)", noAlt:"ალტერნატივები არ არის", noProducts:"პროდუქტები არ ჩაიტვირთა", noProductsSub:"გადაახვიეთ გვერდი და კვლავ დაასკანირეთ.", scanAgain:"ხელახლა სკანირება", bestValue:"საუკეთესო ღირებულება", cheapest:"ყველაზე იაფი", bestDiscount:"საუკეთესო ფასდაკლება", mostSold:"ყველაზე გაყიდვადი", cheapestTag:"ყველაზე იაფი", bestDeal:"საუკეთესო შეთავაზება", mostSoldTag:"ყველაზე გაყიდვადი", bestValueTag:"საუკეთესო ღირებულება", bestPrice:"საუკეთესო ფასი", vs:"vs", sold:"გაიყიდა", footer:"ფასები როგორც ნაჩვენებია · შესაძლოა საკომისიო" },

  // ─────── ARMENIAN ───────
  hy: { title:"Խելացի Գնորդ", scanning:"Սկանավորում…", sameProduct:"Նույն ապրանքը · այլ վաճառողներ", similarMatched:"Նման ապրանքներ · համընկնում", related:"Առնչվող ապրանքներ", similarApi:"Նման ապրանքներ (API)", noAlt:"Այլընտրանք չկա", noProducts:"Ապրանքներ բեռնված չեն", noProductsSub:"Ոլորեք էջը և նորից սկանավորեք։", scanAgain:"Սկանավորել նորից", bestValue:"Լավագույն արժեք", cheapest:"Ամենաէժան", bestDiscount:"Լավագույն զեղչ", mostSold:"Ամենավաճառվող", cheapestTag:"Ամենաէժան", bestDeal:"Լավագույն առաջարկ", mostSoldTag:"Ամենավաճառվող", bestValueTag:"Լավագույն արժեք", bestPrice:"Լավագույն գին", vs:"vs", sold:"վաճառված", footer:"Գները ինչպես ցուցադրված են · Հնարավոր է միջնորդավճար" },

  // ─────── SWAHILI ───────
  sw: { title:"Mnunuzi Mahiri", scanning:"Inachanganua…", sameProduct:"Bidhaa sawa · wauzaji wengine", similarMatched:"Bidhaa zinazofanana · zilizolingana", related:"Bidhaa zinazohusiana", similarApi:"Bidhaa zinazofanana (API)", noAlt:"Hakuna mbadala", noProducts:"Hakuna bidhaa", noProductsSub:"Sogeza ukurasa kisha changanua tena.", scanAgain:"Changanua tena", bestValue:"Thamani bora", cheapest:"Nafuu zaidi", bestDiscount:"Punguzo bora", mostSold:"Inayouzwa zaidi", cheapestTag:"Nafuu zaidi", bestDeal:"Ofa bora", mostSoldTag:"Inayouzwa zaidi", bestValueTag:"Thamani bora", bestPrice:"Bei bora", vs:"vs", sold:"imeuzwa", footer:"Bei kama zilivyoonyeshwa · Tunaweza kupata kamisheni" },

  // ─────── AMHARIC ───────
  am: { title:"ብልህ ገዢ", scanning:"በመቃኘት ላይ…", sameProduct:"ተመሳሳይ ምርት · ሌሎች ሻጮች", similarMatched:"ተመሳሳይ ምርቶች · ተመሳስለዋል", related:"ተዛማጅ ምርቶች", similarApi:"ተመሳሳይ ምርቶች (API)", noAlt:"አማራጮች የሉም", noProducts:"ምንም ምርቶች አልተጫኑም", noProductsSub:"ገጹን ይሸብልሉ እና እንደገና ይቃኙ።", scanAgain:"እንደገና ቃኝ", bestValue:"ምርጥ ዋጋ", cheapest:"በጣም ርካሽ", bestDiscount:"ምርጥ ቅናሽ", mostSold:"በብዛት የተሸጠ", cheapestTag:"በጣም ርካሽ", bestDeal:"ምርጥ ስምምነት", mostSoldTag:"በብዛት የተሸጠ", bestValueTag:"ምርጥ ዋጋ", bestPrice:"ምርጥ ዋጋ", vs:"vs", sold:"ተሽጧል", footer:"ዋጋዎች እንደሚታዩ · ኮሚሽን ይቻላል" },

  // ─────── TAMIL ───────
  ta: { title:"ஸ்மார்ட் ஷாப்பர்", scanning:"ஸ்கேன் செய்கிறது…", sameProduct:"அதே பொருள் · பிற விற்பனையாளர்கள்", similarMatched:"ஒத்த பொருட்கள் · பொருந்தியது", related:"தொடர்புடைய பொருட்கள்", similarApi:"ஒத்த பொருட்கள் (API)", noAlt:"மாற்று இல்லை", noProducts:"பொருட்கள் ஏற்றப்படவில்லை", noProductsSub:"பக்கத்தை உருட்டி மீண்டும் ஸ்கேன் செய்யவும்.", scanAgain:"மீண்டும் ஸ்கேன்", bestValue:"சிறந்த மதிப்பு", cheapest:"மலிவானது", bestDiscount:"சிறந்த தள்ளுபடி", mostSold:"அதிகம் விற்பனையானது", cheapestTag:"மலிவானது", bestDeal:"சிறந்த ஒப்பந்தம்", mostSoldTag:"அதிகம் விற்பனையானது", bestValueTag:"சிறந்த மதிப்பு", bestPrice:"சிறந்த விலை", vs:"vs", sold:"விற்பனை", footer:"காட்டப்பட்ட விலைகள் · கமிஷன் இருக்கலாம்" },

  // ─────── TELUGU ───────
  te: { title:"స్మార్ట్ షాపర్", scanning:"స్కాన్ చేస్తోంది…", sameProduct:"అదే ఉత్పత్తి · ఇతర విక్రేతలు", similarMatched:"సారూప్య ఉత్పత్తులు · సరిపోలాయి", related:"సంబంధిత ఉత్పత్తులు", similarApi:"సారూప్య ఉత్పత్తులు (API)", noAlt:"ప్రత్యామ్నాయాలు లేవు", noProducts:"ఉత్పత్తులు లోడ్ కాలేదు", noProductsSub:"పేజీని స్క్రోల్ చేసి మళ్లీ స్కాన్ చేయండి.", scanAgain:"మళ్లీ స్కాన్", bestValue:"ఉత్తమ విలువ", cheapest:"చౌకైనది", bestDiscount:"ఉత్తమ రాయితీ", mostSold:"ఎక్కువ అమ్ముడైనది", cheapestTag:"చౌకైనది", bestDeal:"ఉత్తమ ఒప్పందం", mostSoldTag:"ఎక్కువ అమ్ముడైనది", bestValueTag:"ఉత్తమ విలువ", bestPrice:"ఉత్తమ ధర", vs:"vs", sold:"అమ్ముడయ్యాయి", footer:"చూపిన ధరలు · కమిషన్ సాధ్యం" },

  // ─────── MALAYALAM ───────
  ml: { title:"സ്മാർട്ട് ഷോപ്പർ", scanning:"സ്കാൻ ചെയ്യുന്നു…", sameProduct:"അതേ ഉൽപ്പന്നം · മറ്റ് വിൽപ്പനക്കാർ", similarMatched:"സമാന ഉൽപ്പന്നങ്ങൾ · പൊരുത്തം", related:"ബന്ധപ്പെട്ട ഉൽപ്പന്നങ്ങൾ", similarApi:"സമാന ഉൽപ്പന്നങ്ങൾ (API)", noAlt:"ബദലുകളില്ല", noProducts:"ഉൽപ്പന്നങ്ങൾ ലോഡ് ചെയ്തിട്ടില്ല", noProductsSub:"പേജ് സ്ക്രോൾ ചെയ്ത് വീണ്ടും സ്കാൻ ചെയ്യുക.", scanAgain:"വീണ്ടും സ്കാൻ", bestValue:"മികച്ച മൂല്യം", cheapest:"ഏറ്റവും വിലകുറഞ്ഞ", bestDiscount:"മികച്ച കിഴിവ്", mostSold:"ഏറ്റവും വിറ്റഴിഞ്ഞ", cheapestTag:"ഏറ്റവും വിലകുറഞ്ഞ", bestDeal:"മികച്ച ഓഫർ", mostSoldTag:"ഏറ്റവും വിറ്റഴിഞ്ഞ", bestValueTag:"മികച്ച മൂല്യം", bestPrice:"മികച്ച വില", vs:"vs", sold:"വിറ്റു", footer:"കാണിച്ച വിലകൾ · കമ്മീഷൻ സാധ്യം" },

  // ─────── MARATHI ───────
  mr: { title:"स्मार्ट शॉपर", scanning:"स्कॅन करत आहे…", sameProduct:"समान उत्पादन · इतर विक्रेते", similarMatched:"समान उत्पादने · जुळले", related:"संबंधित उत्पादने", similarApi:"समान उत्पादने (API)", noAlt:"पर्याय नाही", noProducts:"उत्पादने लोड झाली नाहीत", noProductsSub:"पृष्ठ स्क्रोल करा आणि पुन्हा स्कॅन करा.", scanAgain:"पुन्हा स्कॅन", bestValue:"उत्तम मूल्य", cheapest:"सर्वात स्वस्त", bestDiscount:"उत्तम सवलत", mostSold:"सर्वाधिक विकलेले", cheapestTag:"सर्वात स्वस्त", bestDeal:"उत्तम सौदा", mostSoldTag:"सर्वाधिक विकलेले", bestValueTag:"उत्तम मूल्य", bestPrice:"उत्तम किंमत", vs:"vs", sold:"विकले", footer:"दर्शविलेल्या किंमती · कमिशन शक्य" },

  // ─────── GUJARATI ───────
  gu: { title:"સ્માર્ટ શોપર", scanning:"સ્કેન થઈ રહ્યું છે…", sameProduct:"સમાન ઉત્પાદન · અન્ય વિક્રેતાઓ", similarMatched:"સમાન ઉત્પાદનો · મેળ", related:"સંબંધિત ઉત્પાદનો", similarApi:"સમાન ઉત્પાદનો (API)", noAlt:"કોઈ વિકલ્પ નથી", noProducts:"કોઈ ઉત્પાદન લોડ થયું નથી", noProductsSub:"પૃષ્ઠ સ્ક્રોલ કરો અને ફરી સ્કેન કરો.", scanAgain:"ફરી સ્કેન કરો", bestValue:"શ્રેષ્ઠ મૂલ્ય", cheapest:"સૌથી સસ્તું", bestDiscount:"શ્રેષ્ઠ ડિસ્કાઉન્ટ", mostSold:"સૌથી વધુ વેચાયેલું", cheapestTag:"સૌથી સસ્તું", bestDeal:"શ્રેષ્ઠ સોદો", mostSoldTag:"સૌથી વધુ વેચાયેલું", bestValueTag:"શ્રેષ્ઠ મૂલ્ય", bestPrice:"શ્રેષ્ઠ ભાવ", vs:"vs", sold:"વેચાયું", footer:"દર્શાવેલ ભાવ · કમિશન શક્ય" },

  // ─────── PUNJABI ───────
  pa: { title:"ਸਮਾਰਟ ਸ਼ਾਪਰ", scanning:"ਸਕੈਨ ਹੋ ਰਿਹਾ ਹੈ…", sameProduct:"ਉਹੀ ਉਤਪਾਦ · ਹੋਰ ਵਿਕਰੇਤਾ", similarMatched:"ਸਮਾਨ ਉਤਪਾਦ · ਮੇਲ", related:"ਸੰਬੰਧਿਤ ਉਤਪਾਦ", similarApi:"ਸਮਾਨ ਉਤਪਾਦ (API)", noAlt:"ਕੋਈ ਬਦਲ ਨਹੀਂ", noProducts:"ਕੋਈ ਉਤਪਾਦ ਲੋਡ ਨਹੀਂ ਹੋਇਆ", noProductsSub:"ਸਫ਼ਾ ਸਕ੍ਰੋਲ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਸਕੈਨ ਕਰੋ।", scanAgain:"ਦੁਬਾਰਾ ਸਕੈਨ", bestValue:"ਵਧੀਆ ਮੁੱਲ", cheapest:"ਸਭ ਤੋਂ ਸਸਤਾ", bestDiscount:"ਵਧੀਆ ਛੋਟ", mostSold:"ਸਭ ਤੋਂ ਵੱਧ ਵਿਕਣ ਵਾਲਾ", cheapestTag:"ਸਭ ਤੋਂ ਸਸਤਾ", bestDeal:"ਵਧੀਆ ਸੌਦਾ", mostSoldTag:"ਸਭ ਤੋਂ ਵੱਧ ਵਿਕਣ ਵਾਲਾ", bestValueTag:"ਵਧੀਆ ਮੁੱਲ", bestPrice:"ਵਧੀਆ ਕੀਮਤ", vs:"vs", sold:"ਵਿਕਿਆ", footer:"ਦਿਖਾਈਆਂ ਕੀਮਤਾਂ · ਕਮਿਸ਼ਨ ਸੰਭਵ" },

  // ─────── NEPALI ───────
  ne: { title:"स्मार्ट शपर", scanning:"स्क्यान गर्दै…", sameProduct:"एउटै उत्पादन · अन्य विक्रेता", similarMatched:"समान उत्पादनहरू · मिल्यो", related:"सम्बन्धित उत्पादनहरू", similarApi:"समान उत्पादनहरू (API)", noAlt:"कुनै विकल्प छैन", noProducts:"कुनै उत्पादन लोड भएको छैन", noProductsSub:"पृष्ठ स्क्रोल गर्नुहोस् र फेरि स्क्यान गर्नुहोस्।", scanAgain:"फेरि स्क्यान", bestValue:"उत्कृष्ट मूल्य", cheapest:"सबैभन्दा सस्तो", bestDiscount:"उत्कृष्ट छुट", mostSold:"सबैभन्दा धेरै बिक्री", cheapestTag:"सबैभन्दा सस्तो", bestDeal:"उत्कृष्ट सम्झौता", mostSoldTag:"सबैभन्दा धेरै बिक्री", bestValueTag:"उत्कृष्ट मूल्य", bestPrice:"उत्कृष्ट मूल्य", vs:"vs", sold:"बिक्री", footer:"देखाइएका मूल्यहरू · कमिसन सम्भव" },

  // ─────── SINHALA ───────
  si: { title:"ස්මාර්ට් ෂොපර්", scanning:"ස්කෑන් කරමින්…", sameProduct:"එකම නිෂ්පාදනය · වෙනත් විකුණුම්කරුවන්", similarMatched:"සමාන නිෂ්පාදන · ගැළපුණි", related:"අදාළ නිෂ්පාදන", similarApi:"සමාන නිෂ්පාදන (API)", noAlt:"විකල්ප නැත", noProducts:"නිෂ්පාදන පූරණය නොවිණි", noProductsSub:"පිටුව අනුචලනය කර නැවත ස්කෑන් කරන්න.", scanAgain:"නැවත ස්කෑන්", bestValue:"හොඳම වටිනාකම", cheapest:"ලාභම", bestDiscount:"හොඳම වට්ටම", mostSold:"වැඩිපුරම අලෙවි වූ", cheapestTag:"ලාභම", bestDeal:"හොඳම ගනුදෙනුව", mostSoldTag:"වැඩිපුරම අලෙවි වූ", bestValueTag:"හොඳම වටිනාකම", bestPrice:"හොඳම මිල", vs:"vs", sold:"අලෙවි විය", footer:"පෙන්වන මිල · කොමිස් හැකිය" },

  // ─────── KHMER ───────
  km: { title:"អ្នកទិញឆ្លាតវៃ", scanning:"កំពុងស្កេន…", sameProduct:"ផលិតផលដូចគ្នា · អ្នកលក់ផ្សេង", similarMatched:"ផលិតផលស្រដៀង · ត្រូវគ្នា", related:"ផលិតផលពាក់ព័ន្ធ", similarApi:"ផលិតផលស្រដៀង (API)", noAlt:"គ្មានជម្រើស", noProducts:"គ្មានផលិតផលផ្ទុក", noProductsSub:"រំកិលទំព័រ ហើយស្កេនម្តងទៀត។", scanAgain:"ស្កេនម្តងទៀត", bestValue:"តម្លៃល្អបំផុត", cheapest:"ថោកបំផុត", bestDiscount:"ការបញ្ចុះតម្លៃល្អបំផុត", mostSold:"លក់ដាច់បំផុត", cheapestTag:"ថោកបំផុត", bestDeal:"កិច្ចព្រមព្រៀងល្អបំផុត", mostSoldTag:"លក់ដាច់បំផុត", bestValueTag:"តម្លៃល្អបំផុត", bestPrice:"តម្លៃល្អបំផុត", vs:"vs", sold:"បានលក់", footer:"តម្លៃដូចដែលបានបង្ហាញ · អាចមានកម្រៃ" },

  // ─────── LAO ───────
  lo: { title:"ນັກຊື້ອັດສະລິຍະ", scanning:"ກຳລັງສະແກນ…", sameProduct:"ສິນຄ້າດຽວກັນ · ຜູ້ຂາຍອື່ນ", similarMatched:"ສິນຄ້າຄ້າຍຄື · ກົງກັນ", related:"ສິນຄ້າທີ່ກ່ຽວຂ້ອງ", similarApi:"ສິນຄ້າຄ້າຍຄື (API)", noAlt:"ບໍ່ມີທາງເລືອກ", noProducts:"ບໍ່ມີສິນຄ້າໂຫຼດ", noProductsSub:"ເລື່ອນໜ້າ ແລ້ວສະແກນອີກຄັ້ງ.", scanAgain:"ສະແກນອີກຄັ້ງ", bestValue:"ມູນຄ່າດີທີ່ສຸດ", cheapest:"ຖືກທີ່ສຸດ", bestDiscount:"ສ່ວນຫຼຸດດີທີ່ສຸດ", mostSold:"ຂາຍດີທີ່ສຸດ", cheapestTag:"ຖືກທີ່ສຸດ", bestDeal:"ຂໍ້ຕົກລົງດີທີ່ສຸດ", mostSoldTag:"ຂາຍດີທີ່ສຸດ", bestValueTag:"ມູນຄ່າດີທີ່ສຸດ", bestPrice:"ລາຄາດີທີ່ສຸດ", vs:"vs", sold:"ຂາຍແລ້ວ", footer:"ລາຄາຕາມທີ່ສະແດງ · ຄ່າຄອມມິດຊັນອາດມີ" },

  // ─────── BURMESE ───────
  my: { title:"စမတ်ဈေးဝယ်သူ", scanning:"စကင်ဖတ်နေသည်…", sameProduct:"တူညီသောထုတ်ကုန် · အခြားရောင်းချသူများ", similarMatched:"ဆင်တူထုတ်ကုန်များ · ကိုက်ညီ", related:"ဆက်စပ်ထုတ်ကုန်များ", similarApi:"ဆင်တူထုတ်ကုန်များ (API)", noAlt:"အခြားရွေးချယ်စရာမရှိ", noProducts:"ထုတ်ကုန်များမတင်ရသေး", noProductsSub:"စာမျက်နှာကိုလှိမ့်ပြီး ထပ်မံစကင်ဖတ်ပါ။", scanAgain:"ထပ်မံစကင်ဖတ်", bestValue:"အကောင်းဆုံးတန်ဖိုး", cheapest:"အသက်သာဆုံး", bestDiscount:"အကောင်းဆုံးလျှော့စျေး", mostSold:"အရောင်းရဆုံး", cheapestTag:"အသက်သာဆုံး", bestDeal:"အကောင်းဆုံးသဘောတူညီမှု", mostSoldTag:"အရောင်းရဆုံး", bestValueTag:"အကောင်းဆုံးတန်ဖိုး", bestPrice:"အကောင်းဆုံးစျေး", vs:"vs", sold:"ရောင်းပြီး", footer:"ပြသထားသောစျေးနှုန်းများ · ကော်မရှင်ရနိုင်" },

  // ─────── FILIPINO ───────
  tl: { title:"Smart Shopper", scanning:"Nag-scan…", sameProduct:"Parehong produkto · ibang nagbebenta", similarMatched:"Katulad na produkto · tumugma", related:"Kaugnay na produkto", similarApi:"Katulad na produkto (API)", noAlt:"Walang alternatibo", noProducts:"Walang produkto na-load", noProductsSub:"I-scroll ang page at mag-scan muli.", scanAgain:"Mag-scan muli", bestValue:"Pinakamahusay na halaga", cheapest:"Pinakamura", bestDiscount:"Pinakamahusay na diskwento", mostSold:"Pinakamabenta", cheapestTag:"Pinakamamura", bestDeal:"Pinakamahusay na deal", mostSoldTag:"Pinakamabenta", bestValueTag:"Pinakamahusay na halaga", bestPrice:"Pinakamahusay na presyo", vs:"vs", sold:"nabenta", footer:"Presyo tulad ng ipinakita · Maaaring may komisyon" },
};

// Detect Chrome language
function ssGetLang() {
  try {
    const l = (chrome?.i18n?.getUILanguage?.() || navigator.language || "en").toLowerCase();
    // Try full locale first (zh-tw), then base (zh)
    if (SS_TRANSLATIONS[l]) return l;
    const base = l.split("-")[0];
    if (SS_TRANSLATIONS[base]) return base;
    return "en";
  } catch (_) {
    return "en";
  }
}

const SS_LANG = ssGetLang();
const SS_RTL = new Set(["ar","he","fa","ur"]).has(SS_LANG);

function SS_T(key) {
  const dict = SS_TRANSLATIONS[SS_LANG] || SS_TRANSLATIONS.en;
  return dict[key] || SS_TRANSLATIONS.en[key] || key;
}